config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'vacancies#index'
  get 'static_pages/home'
  resources :vacancies
  resources :companies
  resources :users
  post 'approve_company/:id' => 'companies#approve_company', as: :approve_company
  post 'reject_company/:id'  => 'companies#reject_company',  as: :reject_company
  resources :proposals
  get 'applicant_index' => 'proposals#applicant_index', as: :applicant_proposals
  resources :responses

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  resourcify

  belongs_to :company
  belongs_to :speciality
  has_many   :responses, dependent: :destroy
  accepts_nested_attributes_for :responses, allow_destroy: true

  validates :title, :description, :company_id, :speciality_id, presence: true
  validates :title, length: { maximum: 100 }
  validates :description, length: { minimum: 150 }
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController

  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_vacancy, only: [:show, :edit, :update]

  def index
    @vacancies_grid = initialize_grid(Vacancy)
  end

  def show
  end

  def new
    @vacancy = Vacancy.new
    # @company = current_user.company if current_user == "manager"
    @company = Company.first
  end

  def create
    @vacancy = Vacancy.create(vacancy_params)
    if @vacancy.save
      flash[:success] = "New vacancy has successfully added"
      redirect_to @vacancy
    else
      render 'new'
    end
  end

  def edit
      if current_user.has_role?(:applicant)
        @response = Response.new
      else
      # @company = current_user.company if current_user == "manager"
      @company = Company.first
    end
  end

  def update
    if @vacancy.update_attributes(vacancy_params)
      Response.create(proposal_id: params[:vacancy][:response][:proposal_id], vacancy_id: @vacancy.id)
      flash[:success] = "Vacancy updated"
      redirect_to vacancies_path
    else
      render 'edit'
    end
  end

  def destroy
    Vacancy.find(params[:id]).destroy
    flash[:success] = "Vacancy deleted."
    redirect_to companies_path
  end

  protected

    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    def vacancy_params
      params.require(:vacancy).permit(:title, :description, :speciality_id, :company_id,
                                      responses_attributes: [:proposal_id])
    end
end

app/views/vacancies/_form.html.erb
<%= form_for @vacancy, html: {class: "form-horizontal", role: "form"} do |f| %>

  <%= render 'shared/error_messages', object: @vacancy %>

  <div class="form-group">
    <%= f.label :speciality, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.select :speciality_id, options_from_collection_for_select(Speciality.all, "id", "name", selected: @vacancy.speciality_id), {class: "form_select form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :title, required: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :description, required: true, class: "form-control col-sm-10", rows: "10" %>
    </div>
  </div>

  <%= f.hidden_field :company_id, value: @company.id %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Submit', class: 'btn btn-default' %>
      <%= link_to 'Back', users_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/vacancies/_form_for_applicant.html.erb
<div class="header">
  <h2 >
    <%= @vacancy.title %>
  </h2>
  <h3>
    Company: <%= link_to @vacancy.company.name, company_path(@vacancy.company) %>
  </h3>
  <h4>
    Speciality: <b><%= @vacancy.speciality.name %></b>
  </h4>
  <p>
    <%= @vacancy.description %>
  </p>
</div>
<%= form_for @vacancy do |f| %>

  <%= render 'shared/error_messages', object: @vacancy %>

<%= f.fields_for @response do |fr| %>

  <%= fr.select :proposal_id, Proposal.where(user_id: current_user.id).map { |pr| [pr.speciality.name, pr.id] }.sort, {}, :class => "form-control" %>

  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Send a summary', class: 'btn btn-default' %>
      <%= link_to 'Back', users_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/vacancies/_grid.html.erb
<%= form_tag('', method: :get) do %>
  <button class="wg-external-submit-button btn btn-default" data-grid-name="grid">Submit</button>
  <button class="wg-external-reset-button btn btn-default" data-grid-name="grid">Reset</button>

  <%= grid(@vacancies_grid, hide_submit_button: true, hide_reset_button: true) do |g|

    g.column name: 'Speciality', attribute: 'speciality_id', custom_filter: Speciality.all.map { |sp| [sp.name, sp.id] } do |vacancy|
      vacancy.speciality.name
    end

    g.column name: 'Vacancy', attribute: 'title'  do |vacancy|
      link_to vacancy.title, current_user && current_user.has_role?(:applicant) ? edit_vacancy_path(vacancy) : vacancy
    end

    g.column name: 'Company', attribute: 'company_id', custom_filter: Company.all.map { |c| [c.name, c.id] } do |vacancy|
      vacancy.company.name
    end

    g.column name: 'Responses' do |vacancy|
      vacancy.responses.count
    end

    g.column name: 'Deadline' do |vacancy|
      vacancy.deadline
    end

  end -%>
<% end -%>

app/views/vacancies/_responses.html.erb
<% @vacancy.responses.each do |response| %>
  <tr>
    <td><%= link_to response.proposal.user.email, response.proposal %></td>
    <td>
      <% if response.proposal.summary.url %>
        <%= link_to 'Download summary', response.proposal.summary.url %>
      <% end %>
    </td>
    <td>
      <% if can? :edit, Response %>
        <%= link_to 'Edit', edit_response_path(response) %></td>
      <% end %>
  </tr>
<% end %>

app/views/vacancies/edit.html.erb
<h2>Edit vacancy</h2>
<% if current_user.has_role? :applicant %>
  <%= render 'form_for_applicant' %>
<% else %>
  <%= render 'form' %>
<% end %>

app/views/vacancies/index.html.erb
<h2>All vacancies</h2>
<div class="row">
  <div class="span12">
    <%= render "grid" %>
  </div>
</div>

app/views/vacancies/new.html.erb
<h2>New vacancy for <%= @company.name %></h2>
<%= render 'form' %>

app/views/vacancies/show.html.erb
<div class="header">
  <h2 >
    <%= @vacancy.title %>
  </h2>
  <h3>
    Company: <%= link_to @vacancy.company.name, company_path(@vacancy.company) %>
  </h3>
  <h4>
    Speciality: <b><%= @vacancy.speciality.name %></b>
  </h4>
  <p>
    <%= @vacancy.description %>
  </p>
  <% if current_user && (current_user.has_role?(:manager) || current_user.has_role?(:company_owner)) %>
    <div class="container">
      <div class="row">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Applicant</th>
                <th>Sammary</th>
                <th>Edit response</th>
              </tr>
            </thead>
            <tbody>
              <%= render 'responses' %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div>
  <% if can? :edit, Vacancy %>
    <%= link_to 'Edit', edit_vacancy_path(@vacancy), class: "btn btn-default" %>
  <% end %>
  <% if can? :destroy, Vacancy %>
    <%= link_to 'Delete', vacancy_path(@vacancy), method: 'delete', class: "btn btn-default" %>
  <% end %>
</div>