config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'vacancies#index'
  get 'static_pages/home'
  resources :vacancies
  resources :companies
  resources :users
  post 'approve_company/:id' => 'companies#approve_company', as: :approve_company
  post 'reject_company/:id'  => 'companies#reject_company',  as: :reject_company
  resources :proposals
  get 'applicant_index' => 'proposals#applicant_index', as: :applicant_proposals
  resources :responses

end

app/models/company.rb
class Company < ActiveRecord::Base
  resourcify

  belongs_to :user
  belongs_to :city
  has_many   :managers
  has_many   :vacancies, dependent: :destroy

  validates :name, :city_id, presence: true
  validates :name, uniqueness: true
  validates :description, presence: true, length: { minimum: 50 }

  def approve
    self.approval = true
    self.user.add_role :company_owner
    self.save
  end

  def reject
    self.approval = false
    self.user.remove_role :company_owner if self.user.companies.count == 1
    self.save
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_company, only: [:show, :edit, :update]
  before_action :set_grid, only: [:index, :approve_company, :reject_company]

  def show
  end

  def index
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.create(company_params)
    if @company.save
      flash[:success] = "New company has successfully added"
      redirect_to @company
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @company.update_attributes(company_params)
      flash[:success] = "Company updated"
      redirect_to @company
    else
      render 'edit'
    end
  end

  def destroy
    Company.find(params[:id]).destroy
    flash[:success] = "Company deleted."
    redirect_to companies_path
  end

  def approve_company
    @company = Company.find(params[:id])
    @company.approve
    respond_to do |format|
      format.html { redirect_to companies_path }
      format.js
    end
  end

  def reject_company
    @company = Company.find(params[:id])
    @company.reject
    respond_to do |format|
      format.html { redirect_to companies_path }
      format.js
    end
  end

  protected

    def set_company
      @company = Company.find(params[:id])
    end

    def set_grid
      if current_user && current_user.has_role?(:admin)
        @companies_grid = initialize_grid(Company)
      else
        @companies_grid = initialize_grid(Company.where(approval: true))
      end
    end

    def company_params
      params.require(:company).permit(:name, :description, :city_id, :user_id)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper

  def change_approval(company)
    if company.approval
      link_to 'reject', reject_company_path(company), method: :post, remote: true
    else
      link_to 'approve', approve_company_path(company), method: :post, remote: true
    end
  end

  def edited_company(id)
    "company_#{id}"
  end
end

app/views/companies/_form.html.erb
<%= form_for @company, html: {class: "form-horizontal", role: "form"} do |f| %>

  <%= render 'shared/error_messages', object: @company %>

  <div class="form-group">
    <%= f.label :city, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.select :city_id, options_from_collection_for_select(City.all, "id", "city", selected: @company.city_id), {class: "form_select form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :name, required: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :description, required: true, class: "form-control col-sm-10", rows: "10" %>
    </div>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Submit', class: 'btn btn-default' %>
      <%= link_to 'Back', companies_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/companies/_grid.html.erb
<%= form_tag('', method: :get) do %>
  <button class="wg-external-submit-button btn btn-default" data-grid-name="grid">Submit</button>
  <button class="wg-external-reset-button btn btn-default" data-grid-name="grid">Reset</button>

  <%= grid(@companies_grid, hide_submit_button: true, hide_reset_button: true) do |g|

    g.column name: 'Name', attribute: 'name' do |company|
      link_to company.name, company
    end

    g.column name: 'Country', attribute: 'country_id', assoc: :city, custom_filter: Country.all.map { |c| [c.country, c.id] } do |company|
      company.city.country.country
    end

    g.column name: 'City', attribute: 'city_id', custom_filter: City.all.map { |c| [c.city, c.id] }  do |company|
      company.city.city
    end

    g.column name: 'Description' do |company|
      truncate(company.description, length: 70)
    end

    if current_user && current_user.has_role?(:admin)
      g.column name: 'Approval', attribute: 'approval' do |company|
        [change_approval(company), {class: edited_company(company.id)}]
      end
    end

  end -%>
<% end -%>

app/views/companies/approve_company.js.erb
$('.<%= edited_company(@company.id) %>').html('<%= j change_approval(@company) %>');

app/views/companies/edit.html.erb
<h2>Edit company</h2>
<%= render 'form' %>

app/views/companies/index.html.erb
<h2>All companies</h2>
<div class="row">
  <div class="span12">
    <div align='right'>
      <% if can? :new, Company %>
        <%= link_to "New company", new_company_path %>
      <% end %>
    </div>
    <%= render "grid" %>
  </div>
</div>

app/views/companies/new.html.erb
<h2>New company</h2>
<%= render 'form' %>

app/views/companies/reject_company.js.erb
$('.<%= edited_company(@company.id) %>').html('<%= j change_approval(@company) %>');

app/views/companies/show.html.erb
<div class="header">
  <h1>
    <%= @company.name %>
  </h1>
  <h3>
    <%= @company.city.country.country %>,
    <%= @company.city.city %>
  </h3>
  <p>
    <%= @company.description %>
  </p>
</div>

<div>
  <% if can? :new, Vacancy %>
    <%= link_to 'Create new vacancy', new_vacancy_path, class: "btn btn-default" %>
  <% end %>
  <% if can? :edit, Company %>
    <%= link_to 'Edit', edit_company_path(@company), class: "btn btn-default" %>
  <% end %>
  <% if can? :destroy, Company %>
    <%= link_to 'Delete', company_path(@company), method: 'delete', class: "btn btn-default" %>
  <% end %>
  <%= link_to 'Back', companies_path, class: 'btn btn-default' %>
</div>