config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'vacancies#index'
  get 'static_pages/home'
  resources :vacancies
  resources :companies
  resources :users
  post 'approve_company/:id' => 'companies#approve_company', as: :approve_company
  post 'reject_company/:id'  => 'companies#reject_company',  as: :reject_company
  resources :proposals
  get 'applicant_index' => 'proposals#applicant_index', as: :applicant_proposals
  resources :responses

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'

  belongs_to :user
  belongs_to :speciality
  has_many   :responses, dependent: :destroy
  accepts_nested_attributes_for :responses, allow_destroy: true

  validates :user_id, :speciality_id, presence: true

  mount_uploader :summary, SummaryUploader

end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_proposal, only: [:show, :edit, :update]

  def index
      @proposals_grid = initialize_grid(Proposal)
  end

  def applicant_index
      @proposals_grid = initialize_grid(Proposal.where(user_id: current_user.id))
  end

  def show
  end

  def new
    @proposal = Proposal.new
  end

  def create
    @proposal = Proposal.create(proposal_params)
    if @proposal.save
      flash[:success] = "New proposal has successfully added"
      redirect_to proposals_path
    else
      render 'new'
    end
  end

  def edit
    if current_user.has_role?(:manager)
      @response = Response.new
    end
  end

  def update
    if @proposal.update_attributes(proposal_params)
      Response.create(proposal_id: params[:proposal][:response][:vacancy_id], proposal_id: @proposal.id)
      flash[:success] = "Proposal updated"
      redirect_to proposals_path
    else
      render 'edit'
    end
  end

  def destroy
    if @proposal.user.id != current_user.id
      flash[:success] = "You can not destroy someone else's proposal"
      redirect_to proposals_path
    else
      proposal.find(params[:id]).destroy
      flash[:success] = "proposal deleted."
      redirect_to proposals_path
    end
  end

  protected

    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    def proposal_params
      params.require(:proposal).permit(:user_id, :speciality_id, :summary, :salary,
                                        responses_attributes: [:vacancy_id])
    end
end

app/views/proposals/_form.html.erb
<%= form_for @proposal, html: {class: "form-horizontal", role: "form"} do |f| %>

  <%= render 'shared/error_messages', object: @proposal %>

  <div class="form-group">
    <%= f.label :speciality, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.select :speciality_id, options_from_collection_for_select(Speciality.all, "id", "name", selected: @proposal.speciality_id), {class: "form_select form-control"} %>
    </div>
  </div>

   <div class="form-group">
    <%= f.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :description, required: true, class: "form-control col-sm-10", rows: "10" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :salary, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :salary, required: true, class: "form-control col-sm-10" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :summary, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.file_field :summary %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Submit', class: 'btn btn-default' %>
      <%= link_to 'Back', applicant_proposals_path, class: 'btn btn-default' %>
    </div>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

<% end %>

app/views/proposals/_form_for_manager.html.erb
<div class="header">
  <h2 >
    <%= @proposal.user.email %>
  </h2>
  <h4>
    Speciality: <b><%= @proposal.speciality.name %></b>
  </h4>
  <p>
    Description: <%= @proposal.description %>
  </p>
  <p>
    Salary: <%= @proposal.salary %>
  </p>
  <p>
    Summary: <%= @proposal.summary.url %>
  </p>
</div>
<%= form_for @proposal do |f| %>

  <%= render 'shared/error_messages', object: @proposal %>

  <%= f.fields_for @response do |fr| %>

    <%= fr.select :vacancy_id, company_vacancies.map { |pr| [pr.speciality.name, pr.id] }.sort, {}, :class => "form-control" %>

  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'To invite', class: 'btn btn-default' %>
      <%= link_to 'Back', proposals_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/proposals/_grid.html.erb
<%= form_tag('', method: :get) do %>
  <button class="wg-external-submit-button btn btn-default" data-grid-name="grid">Submit</button>
  <button class="wg-external-reset-button btn btn-default" data-grid-name="grid">Reset</button>

  <%= grid(@proposals_grid, hide_submit_button: true, hide_reset_button: true) do |g|

    g.column name: 'Speciality', attribute: 'speciality_id', custom_filter: Speciality.all.map { |sp| [sp.name, sp.id] } do |proposal|
      proposal.speciality.name
    end

    g.column name: 'Applicant', attribute: 'user_id' do |proposal|
      link_to proposal.user.email, current_user && current_user.has_role?(:manager) ? edit_proposal_path(proposal) : proposal
    end

    g.column name: 'Description' do |proposal|
      truncate(proposal.description, length: 30)
    end

    g.column name: 'Summary' do |proposal|
      link_to 'download summary', proposal.summary.url if proposal.summary.url
    end

    g.column name: 'Salary' do |proposal|
      proposal.salary
    end

    g.column name: '' do |proposal|
      link_to 'Edit', edit_proposal_path(proposal) if current_user && proposal.user.id == current_user.id
    end

     g.column name: '' do |proposal|
      link_to 'Delete', proposal_path(proposal), method: :delete, data: { confirm: "Are you sure?"} if current_user && proposal.user.id == current_user.id
    end

  end -%>
<% end -%>

app/views/proposals/applicant_index.html.erb
<h2>All applinats</h2>
<div class="row">
  <div class="span12">
    <div align='right'>
      <% if can? :new, Proposal %>
        <%= link_to "New proposal", new_proposal_path %>
      <% end %>
    </div>
    <%= render "grid" %>
  </div>
</div>

app/views/proposals/edit.html.erb
<h2>Edit proposal</h2>
<% if current_user.has_role?(:manager) %>
  <%= render 'form_for_manager' %>
<% else %>
  <%= render 'form' %>
<% end %>

app/views/proposals/index.html.erb
<h2>All applinats</h2>
<div class="row">
  <div class="span12">
    <div align='right'>
      <% if can? :new, Proposal %>
        <%= link_to "New proposal", new_proposal_path %>
      <% end %>
    </div>
    <%= render "grid" %>
  </div>
</div>

app/views/proposals/new.html.erb
<h2>New proposal</h2>
<%= render 'form' %>

app/views/proposals/show.html.erb
<div class="header">
  <h1>
    Info about <%= @proposal.user.email %>
  </h1>
  <p>
    <%= @proposal.description %>
  </p>
</div>

<div>

  <% if can? :edit, Proposal %>
    <% if @proposal.user.id == current_user.id %>
      <%= link_to 'Edit', edit_proposal_path(@proposal), class: "btn btn-default" %>
    <% end %>
  <% end %>

  <% if can? :destroy, Proposal %>
    <% if @proposal.user.id == current_user.id %>
      <%= link_to 'Delete', proposal_path(@proposal), method: 'delete', class: "btn btn-default" %>
    <% end %>
  <% end %>
  <%= link_to 'Back', proposals_path, class: 'btn btn-default' %>
</div>