config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'vacancies#index'
  get 'static_pages/home'
  resources :vacancies
  resources :companies
  resources :users
  post 'approve_company/:id' => 'companies#approve_company', as: :approve_company
  post 'reject_company/:id'  => 'companies#reject_company',  as: :reject_company
  resources :proposals
  get 'applicant_index' => 'proposals#applicant_index', as: :applicant_proposals
  resources :responses

end

app/views/layouts/_header.html.erb
<div class='navbar navbar-inverse navbar-fixed-top'>
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Job_platform', root_url, id: "logo" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Vacancies', vacancies_path %>
        </li>
        <li>
          <%= link_to 'Applicants', proposals_path %>
        </li>
        <li>
          <%= link_to 'Companies', companies_path %>
        </li>
        <% if can? :index, User %>
          <li>
            <%= link_to 'Users', users_path %>
          </li>
        <% end %>
        <% if current_user && current_user.has_role?(:applicant) %>
          <li>
            <%= link_to 'Edit summary', applicant_proposals_path %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li>
              <div class="logged">
                Logged in as <strong><%= current_user.email %></strong>
              </div>
            </li>
            <li>
              <%= link_to 'Edit profile', edit_user_registration_path %>
            <li>
            </li>
            <li>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
            </li>
            <% else %>
            <li>
              <%= link_to 'Login', new_user_session_path %>
            </li>
            <li>
              <%= link_to 'Sign_Up', new_user_registration_path %>
            </li>
            <% end %>
          </li>
        </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobPlatform</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>